#!/usr/bin/env python
# vim: set fileencoding=utf-8:
#
# Copyright (C) 2009-2010 Tommi Rantala <tt.rantala@gmail.com>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

import receiptdb

receipts = receiptdb.parse_db("receipts")
receipts.sort()
receipts_canon = []
for k in receipts:
	date,category,cents,info = k
	receipts_canon.append((date,receiptdb.category_canonicalize(category),cents))
receipts = receipts_canon
prev = receipts.pop()
for k in receipts:
	if prev==k:
		print "DUPLICATE:", k
	prev=k
